### ISSUE TITLE
🐛 Unable to pip install editable version

### ISSUE THREAD

**Issue by peter-janderks** [cda-tum/qecc#135]
### mqt.qecc version

mqt.qecc 1.3.1

### OS

20.04.1-Ubuntu

### Python version

Python 3.10

### Description

When I follow the build instructions at [https://qecc.readthedocs.io/en/latest/DevelopmentGuide.html](url) errors occur:

Specifically when I type `pip install --editable .[dev]` this error occurs (The project also doesn't install without using the editable mode):

```  Building editable for mqt.qecc (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for mqt.qecc (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [156 lines of output]
      /tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        config = read_configuration(filepath, True, ignore_option_errors, dist)
      running editable_wheel
      creating /tmp/pip-wheel-7cj88rx4/.tmp-kn816tck/mqt.qecc.egg-info
      writing /tmp/pip-wheel-7cj88rx4/.tmp-kn816tck/mqt.qecc.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-7cj88rx4/.tmp-kn816tck/mqt.qecc.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-wheel-7cj88rx4/.tmp-kn816tck/mqt.qecc.egg-info/entry_points.txt
      writing requirements to /tmp/pip-wheel-7cj88rx4/.tmp-kn816tck/mqt.qecc.egg-info/requires.txt
      writing top-level names to /tmp/pip-wheel-7cj88rx4/.tmp-kn816tck/mqt.qecc.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-7cj88rx4/.tmp-kn816tck/mqt.qecc.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching '**/apps'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-wheel-7cj88rx4/.tmp-kn816tck/mqt.qecc.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-7cj88rx4/.tmp-kn816tck/mqt.qecc-1.3.2.dev5+g97b9c9a.dist-info'
      creating /tmp/pip-wheel-7cj88rx4/.tmp-kn816tck/mqt.qecc-1.3.2.dev5+g97b9c9a.dist-info/WHEEL
      running build_py
      running build_ext
      -- The CXX compiler identification is GNU 9.4.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Performing Test HAS_MARCH_NATIVE
      -- Performing Test HAS_MARCH_NATIVE - Success
      -- Could NOT find GMP (missing: GMPXX_LIB GMPXX_INCLUDE_DIR GMP_INCLUDE_DIR GMP_LIB)
      Did not find GMP. Using Boost multiprecision library instead.
      -- Boost.Multiprecision: standalone mode ON
      -- Using the single-header code from /home/pderks/Documents/phd/qecc/extern/qfr/extern/json/single_include/
      -- pybind11 v2.11.0 dev1
      -- Found PythonInterp: /home/pderks/Documents/phd/qecc/qecc_venv/bin/python3 (found suitable version "3.9.7", minimum required is "3.6")
      -- Found PythonLibs: /home/pderks/anaconda3/lib/libpython3.9.so
      -- The C compiler identification is GNU 9.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      CMake Error at /tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find FLINT (missing: FLINT_LIBRARY FLINT_INCLUDE_DIR)
      Call Stack (most recent call first):
        /tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
        cmake/FindFLINT.cmake:83 (find_package_handle_standard_args)
        src/CMakeLists.txt:32 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 155, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 344, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 267, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 294, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 94, in build_extension
        File "/home/pderks/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/pderks/Documents/phd/qecc', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/tmp2h4mezoc.build-lib/mqt/qecc', '-DPYTHON_EXECUTABLE=/home/pderks/Documents/phd/qecc/qecc_venv/bin/python3', '-DQECC_VERSION_INFO=1.3.2.dev5+g97b9c9a', '-DCMAKE_BUILD_TYPE=Release', '-DBINDINGS=ON', '-GNinja']' returned non-zero exit status 1.
      /tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:988: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `mqt.qecc` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      Traceback (most recent call last):
        File "/home/pderks/Documents/phd/qecc/qecc_venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/pderks/Documents/phd/qecc/qecc_venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/pderks/Documents/phd/qecc/qecc_venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 445, in build_editable
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 102, in <module>
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 155, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 344, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 267, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 294, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-bcf33gnq/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 94, in build_extension
        File "/home/pderks/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/pderks/Documents/phd/qecc', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/tmp2h4mezoc.build-lib/mqt/qecc', '-DPYTHON_EXECUTABLE=/home/pderks/Documents/phd/qecc/qecc_venv/bin/python3', '-DQECC_VERSION_INFO=1.3.2.dev5+g97b9c9a', '-DCMAKE_BUILD_TYPE=Release', '-DBINDINGS=ON', '-GNinja']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for mqt.qecc
Failed to build mqt.qecc
ERROR: Could not build wheels for mqt.qecc, which is required to install pyproject.toml-based projects```

### Expected behavior

I expected to be able to run `pip install --editable .[dev]`

### How to Reproduce

Follow steps 1-7 at [https://qecc.readthedocs.io/en/latest/DevelopmentGuide.html](url) and then run `pip install --editable .[dev]`

**Comment by burgholzer** [comment]
Thanks for opening this issue. The error message says it all

> Could NOT find FLINT (missing: FLINT_LIBRARY FLINT_INCLUDE_DIR)

You are missing the `flint` dependency that's required for building the project. 
On Linux it's as easy to get as `sudo apt-get install libflint-dev`.
On macOS you can get it via `brew install flint`.
On Windows, you might have to install it from source: https://github.com/flintlib/flint2

IIRC @lucasberent has plans to remove this dependency in the future and replace it with something else.
